a = read.csv("student_exam.csv")
b = read.csv("coffee_monthly_location_sales.csv")
mean(a$Class_A)
mean(a$Class_B)
mean(b$No_Seoul)
mean(b$No_Gangneung)
mean(b$No_Busan)
median(a$Class_A)
median(a$Class_B)
median(b$No_Seoul)
median(b$No_Gangneung)
median(b$No_Busan)
var(a$Class_A)
var(a$Class_B)
var(b$No_Seoul)
var(b$No_Gangneung)
var(b$No_Busan)